Repository terraform-providers/terraform-provider-launchdarkly, pull requests merged in 2019-11, with the labels that each got.

#4 Change module path to include full source path
  go.mod
Labels: size/XS

#7 Fix typo in provider initialization error message
  launchdarkly/provider.go
Labels: size/XS

#8 prepare 1.0.0 release
  CHANGELOG.md
  go.mod
  go.sum
  launchdarkly/environments_helper.go
  launchdarkly/prerequisite_helper.go
  launchdarkly/resource_launchdarkly_custom_role.go
  launchdarkly/resource_launchdarkly_environment.go
  launchdarkly/resource_launchdarkly_environment_test.go
  launchdarkly/resource_launchdarkly_feature_flag.go
  launchdarkly/resource_launchdarkly_feature_flag_test.go
  launchdarkly/resource_launchdarkly_project.go
  launchdarkly/resource_launchdarkly_project_test.go
  launchdarkly/resource_launchdarkly_segment.go
  launchdarkly/resource_launchdarkly_segment_test.go
  launchdarkly/resource_launchdarkly_webhook.go
  launchdarkly/rule_helper.go
  launchdarkly/tags_helper.go
  launchdarkly/validation_helper.go
  website/docs/index.html.markdown
  website/docs/r/environment.html.markdown
Labels: documentation, size/XL

#9 Fix custom role typo
  CHANGELOG.md
  website/docs/r/team_member.html.markdown
Labels: documentation, size/XS
